[package]
name = "emojeez"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
unicode-types = { workspace = true }

[lints]
workspace = true
